name: Build ROCK

on:
  workflow_call:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup LXD
        uses: canonical/setup-lxd@main
      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic
      - name: Build ROCK
        run: |
          rockcraft pack
      - name: Upload locally built ROCK artifact
        uses: actions/upload-artifact@v3
        with:
          name: valkey-rock
          path: valkey_*_amd64.rock