name: Publish to GHCR

env:
  RELEASE: edge

on:
  push:
    branches:
      - 9-26.04

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  release:
    name: Release rock
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_rock.yaml@v42.0.1
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    permissions:
      packages: write # Needed to publish to GitHub Container Registry
      contents: write # Needed to create git tags
